dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Arduino-Boards hardware/keyboardio/avr
  - cat extras/boards.txt >>hardware/keyboardio/avr/boards.txt
  - cat extras/platform.txt >>hardware/keyboardio/avr/platform.txt
  - cp -pr extras/variants/ergodox hardware/keyboardio/avr/variants/
script:
  - make travis-test BOARD_HARDWARE_PATH=$(pwd)/hardware
notifications:
  irc:
    channels:
      - "chat.freenode.net#keyboardio"
    use_notice: true
    skip_join: true
    template:
      - "%{repository_name}/%{branch} %{commit} by %{author}: %{commit_subject} %{build_url} %{message}"
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
