language: cpp
dist: trusty
sudo: required
os:
  - linux
before_install:
  - wget http://downloads.arduino.cc/arduino-1.6.11-linux64.tar.xz
  - tar xf arduino-1.6.11-linux64.tar.xz
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Arduino-Boards hardware/keyboardio/avr
script:
  - make build-all BOARD_HARDWARE_PATH=$(pwd)/hardware ARDUINO_PATH=$(pwd)/arduino-1.6.11
