dist: trusty
sudo: false
language: c
os:
  - linux
addons:
  apt:
    packages:
      - shellcheck
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio hardware/keyboardio
## We delete the library.properties of the Bundle's Kaleidoscope.
## We do this to force Arduino to use the current one instead of the bundled version.
  - rm -rf hardware/keyboardio/avr/libraries/Kaleidoscope
  - ln -s $(pwd) hardware/keyboardio/avr/libraries/Kaleidoscope
script:
  - make travis-test KALEIDOSCOPE_TEMP_PATH=$(pwd)/.kaleidoscope-build-cache BOARD_HARDWARE_PATH=$(pwd)/hardware
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
  directories:
    - .kaleidoscope-build-cache
    - .ccache
