dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Arduino-Boards hardware/keyboardio/avr
script:
  - make travis-install-arduino build-all BOARD_HARDWARE_PATH=$(pwd)/hardware ARDUINO_PATH=$(pwd)/arduino
