dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --shallow-submodules --recurse-submodules https://github.com/keyboardio/Arduino-Boards hardware/keyboardio/avr
script:
  - make travis-test ARDUINO_PATH=$(shell pwd)/arduino BOARD_HARDWARE_PATH=$(shell pwd)/hardware
